import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';

const neue = localFont({
  src: [
    { path: './fonts/neue-montreal/NeueMontreal-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/neue-montreal/NeueMontreal-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/neue-montreal/NeueMontreal-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-neue',
  display: 'swap',
  preload: true,
});

const humane = localFont({
  src: [
    { path: './fonts/humane/Humane-Light.woff2', weight: '300', style: 'normal' },
    { path: './fonts/humane/Humane-Regular.woff2', weight: '400', style: 'normal' },
    { path: './fonts/humane/Humane-Medium.woff2', weight: '500', style: 'normal' },
    { path: './fonts/humane/Humane-SemiBold.woff2', weight: '600', style: 'normal' },
    { path: './fonts/humane/Humane-Bold.woff2', weight: '700', style: 'normal' },
    { path: './fonts/humane/Humane-Black.woff2', weight: '900', style: 'normal' },
  ],
  variable: '--font-humane',
  display: 'swap',
  preload: true,
});

const doner = localFont({
  src: [{ path: './fonts/doner/Doner-RegularText.otf', weight: '400', style: 'display' }],
  variable: '--font-doner',
  display: 'swap',
  preload: true,
});

const donerdisplay = localFont({
  src: [{ path: './fonts/doner/Doner-RegularDisplay.otf', weight: '400', style: 'normal' }],
  variable: '--font-donerdisplay',
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Soupologist',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${humane.variable} ${neue.variable} ${doner.variable} ${donerdisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
